- name: create ec2 instances
  hosts: all
  connection: local
  vars:
    sg_id: sg-0ff061d19a895a55d
    ami_id: ami-0220d79f3f480ecf5
    environment: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: crearing aws ec2 instances
    amazon.aws.ec2_instance:
    instance_type: t3.micro
    image_id: "{{ ami_id }}"
    security_group: "{{ sg_id }}"
    name: "{{ item }}-{{ environment }}"
    tags:
      Project: Roboshop
      Component: "{{ item }}"
      Environment: "{{ environment }}"
      Name: "{{ item }}-{{ environment }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
